edit/urls.py
from django.urls import path

from . import views

app_name='edit'
urlpatterns=[
    path('<str:title>', views.edit, name='edit' )
]

encyclopedia/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("random/",views.randomEntry, name="randomEntry")
]

entry/urls.py
from django.urls import path

from . import views

app_name='entry'
urlpatterns=[
    path('<str:title>', views.index, name='index' )
]

newEntry/urls.py
from django.urls import path

from . import views

app_name='newEntry'
urlpatterns=[
    path('', views.add, name='add' )
]

search/urls.py
from django.urls import path

from . import views

app_name='search'
urlpatterns=[
    path('', views.index, name='index' )
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    path('wiki/', include("entry.urls")),
    path('search/', include("search.urls")),
    path('new/', include("newEntry.urls")),
    path('edit/', include("edit.urls")),

]

edit/models.py
from django.db import models

# Create your models here.

encyclopedia/models.py
from django.db import models

# Create your models here.

entry/models.py
from django.db import models

# Create your models here.

newEntry/models.py
from django.db import models

# Create your models here.

search/models.py
from django.db import models

# Create your models here.

edit/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse
from encyclopedia import util
from newEntry.views import EntryForm


def edit (request, title):
    entries=util.list_entries()
    for i in range(0,len(entries)-1):
        entries[i]=entries[i].lower()
    if request.method=='POST':
        form = EntryForm(request.POST)
        if form.is_valid():
            title=form.cleaned_data["title"]
            content=form.cleaned_data["content"]
            entry=f"#{title}\n\n {content}"
            if title.lower() in entries:
                util.save_entry(title, entry)
                return HttpResponseRedirect(reverse('entry:index', args=[title]))
            else:
                message='This page does not exist'
                return render(request, 'edit/edit.html',{
                    'form':form,
                    'title':title,
                    'message':message,

                    })
    item = util.get_entry(title)
    item = str(item).split(" ")
    form = EntryForm({'title': title, 'content':" ".join(item[1:])})
    return render(request, 'edit/edit.html',{
        'form':form,
        'title':title,

        })

encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from random import randint
from . import util

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
    })

def randomEntry(request):
    entryList=util.list_entries()
    idx=randint(0,len(entryList)-1)
    return HttpResponseRedirect(reverse('entry:index', args=[entryList[idx]]))

entry/views.py
from django.shortcuts import render
from django.http import HttpResponse
from encyclopedia import util
import markdown2


def index(request, title):
    return render(request, "entry/index.html",{
    'title':title.upper(),
    'entry':markdown2.markdown(util.get_entry(title)),
    })

newEntry/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from encyclopedia import util

class EntryForm(forms.Form):
    title=forms.CharField(label='Title:')
    content=forms.CharField(label='Type content in Markdown:', widget=forms.Textarea(attrs={'rows':5}))

def add (request):
    entries=util.list_entries()
    for i in range(0,len(entries)-1):
        entries[i]=entries[i].lower()
    if request.method=='POST':
        form = EntryForm(request.POST)
        if form.is_valid():
            title=form.cleaned_data["title"]
            title=title.capitalize()
            content=form.cleaned_data["content"]
            entry=f"#{title}\n\n {content}"

            if title.lower() in entries:
                return render(request, 'newEntry/add.html',{
                'form':form,
                'message':"Article with that title already exists!"
                })
            else:
                util.save_entry(title, entry)
                return HttpResponseRedirect(reverse('entry:index', args=[title]))


    return render(request, 'newEntry/add.html',{
    'form':EntryForm,
    })

search/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

from encyclopedia import util

class SearchForm(forms.Form):
    q=forms.CharField()

def index(request):
    entryList=util.list_entries()
    for i in range(0,len(entryList)):
        entryList[i]=entryList[i].lower()

    items=[]

    if request.method == 'POST':
        res = SearchForm(request.POST)
        if res.is_valid():
            res=res.cleaned_data['q']
            if str(res).lower() in entryList:
                return HttpResponseRedirect(reverse('entry:index', args=[str(res)]))
            for entry in entryList:
                if str(res) in entry:
                    items.append(entry)
    return render(request, "search/index.html", {
        "results": items,
    })

edit/templates/edit/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  Edit
{% endblock %}

{% block body %}
<h1>Edit page</h1>
<div class="alert"><h3>{{message}}</h3></div>
<form action="{% url 'edit:edit' title %}" method="POST">
    {% csrf_token %}
    {% for f in form %}
      <div id="newEntry">
        <div class="label">
          {{f.label}}
        </div>
        <div class="content">
          {{f}}
        </div>
      </div>
    {% endfor %}
    <input type="submit">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'entry:index' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'search:index' %}" method="POST">
                  {% csrf_token %}
                  <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'newEntry:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'randomEntry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

entry/templates/entry/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}

{{entry|safe}}
<a class="edit" href="{% url 'edit:edit' title %}">Edit page</a>
{% endblock %}

newEntry/templates/newEntry/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Add new
{% endblock %}

{% block body %}
<h1>New page</h1>
<h3>{{message}}</h3>
<form action="{% url 'newEntry:add'%}" method="POST">
    {% csrf_token %}
    {% for f in form %}
      <div id="newEntry">
        <div class="label">
          {{f.label}}
        </div>
        <div class="content">
          {{f}}
        </div>
      </div>
    {% endfor %}
    <input type="submit">
</form>
{% endblock %}

search/templates/search/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Results
{% endblock %}

{% block body %}
<h1>Search Results</h1>
  <ul>
    {% for result in results %}
      <li><a href="{% url 'entry:index' result %}">{{ result }}</a></li>
    {% empty %}
      <li>No tasks</li>
    {% endfor %}
  </ul>
{% endblock %}